import type { GrapeLive, GrapeArtist } from './types'

// ─── Artists ────────────────────────────────────────────────────────────────

export const ARTISTS: GrapeArtist[] = [
  { id: 'somei',       name: 'somei',        image: '/grape/artist/somei.JPG',          birthday: '2000-03-28' },
  { id: 'shiyui',      name: 'シユイ',        image: '/grape/artist/シユイ.JPG',         birthday: '2000-04-12' },
  { id: 'yurika',      name: '優利香',        image: '/grape/artist/優利香.JPG',         birthday: '2000-05-23' },
  { id: 'ado',         name: 'Ado',           image: '/grape/artist/Ado.JPG',            birthday: '2000-04-05' },
  { id: 'super-tozan', name: 'スーパー登山部', image: '/grape/artist/スーパー登山部.JPG',  birthday: '2000-04-18' },
  { id: 'yama',        name: 'yama',          image: '/grape/artist/yama.JPG',           birthday: '2000-05-10' },
]

// ─── Lives ───────────────────────────────────────────────────────────────────

export const LIVES: GrapeLive[] = [
  // ── 3月 過去 ──────────────────────────────────────────────────────────────
  {
    id: 'l01',
    title: "Somei 1st ONE MAN LiVE『ASYLUM』",
    artist: 'somei',
    artistImage: '/grape/artist/somei.JPG',
    coverImage: "/grape/cover/Somei 1st ONE MAN LiVE『ASYLUM』.JPG",
    venue: '演家-SHITORAYA-',
    date: '2026-04-03',
    openingTime: '17:30',
    startTime: '18:00',
    endTime: '20:30',
    liveType: 'ワンマン',
    attendanceStatus: 'attended',
    ticketStatus: 'done',
    price: 3500,
  },
  {
    id: 'l02',
    title: '切磋琢磨 4th anniversary',
    artist: '優利香',
    artists: ['優利香', 'somei', 'シユイ'],
    artistImage: '/grape/artist/優利香.JPG',
    artistImages: ['/grape/artist/優利香.JPG', '/grape/artist/somei.JPG', '/grape/artist/シユイ.JPG'],
    coverImage: '/grape/cover/切磋琢磨 4th anniversary.JPG',
    venue: '下北沢LOFT',
    date: '2026-04-06',
    openingTime: '16:30',
    startTime: '17:00',
    endTime: '20:00',
    liveType: '対バン',
    attendanceStatus: 'attended',
    ticketStatus: 'done',
    price: 3000,
  },
  {
    id: 'l03',
    title: 'Shibuya Fidd Out! Vol.3',
    artist: 'シユイ',
    artistImage: '/grape/artist/シユイ.JPG',
    coverImage: '/grape/cover/IMG_9808.JPG',
    venue: '渋谷サクラステージ SHIBUYAサイド',
    date: '2026-04-09',
    startTime: '15:00',
    endTime: '19:00',
    liveType: 'フェス',
    attendanceStatus: 'attended',
    ticketStatus: 'done',
    price: 4500,
  },

  // ── 3月20日 同日3件 ────────────────────────────────────────────────────────
  {
    id: 'l04',
    title: 'Kabukicho Street Live Fes.',
    artist: 'somei',
    artists: ['somei', '優利香'],
    artistImage: '/grape/artist/somei.JPG',
    artistImages: ['/grape/artist/somei.JPG', '/grape/artist/優利香.JPG'],
    coverImage: '/grape/cover/IMG_9747.JPG',
    venue: '歌舞伎町タワーシネシティ広場',
    date: '2026-04-14',
    openingTime: '12:00',
    startTime: '13:00',
    endTime: '18:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    seatInfo: 'スタンディング',
    priority: 'low',
    price: 0,
  },
  {
    id: 'l05',
    title: 'Shibuya Street Live × SFW®',
    artist: '優利香',
    artistImage: '/grape/artist/優利香.JPG',
    coverImage: '/grape/cover/Shibuya Street Live × SFW_優利香.JPG',
    venue: '渋谷サクラステージ SHIBUYAサイド',
    date: '2026-04-14',
    startTime: '15:30',
    endTime: '16:00',
    liveType: '対バン',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    price: 0,
  },
  {
    id: 'l06',
    title: 'Shibuya Street Live × SFW® somei',
    artist: 'somei',
    artistImage: '/grape/artist/somei.JPG',
    coverImage: '/grape/cover/Shibuya Street Live × SFW2_somei.JPG',
    venue: '歌舞伎町タワー和牛特区前',
    date: '2026-04-14',
    openingTime: '16:30',
    startTime: '17:00',
    endTime: '17:30',
    liveType: '対バン',
    attendanceStatus: 'planned',
    ticketStatus: 'payment-due',
    ticketDeadline: '2026-04-20',
    priority: 'high',
    price: 2000,
  },

  // ── 3月末〜4月 ────────────────────────────────────────────────────────────
  {
    id: 'l07',
    title: 'CONTINUE 優利香 ワンマン',
    artist: '優利香',
    artistImage: '/grape/artist/優利香.JPG',
    coverImage: '/grape/cover/CONTINUE_優利香.JPG',
    venue: 'LIVE STUDIO LODGE',
    date: '2026-03-25',
    openingTime: '18:30',
    startTime: '19:00',
    endTime: '21:00',
    liveType: 'ワンマン',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    seatInfo: 'A列4番',
    priority: 'medium',
    price: 3300,
  },
  {
    id: 'l08',
    title: 'シェアート FES 2026',
    artist: 'シユイ',
    artists: ['シユイ', 'yama', 'スーパー登山部'],
    artistImage: '/grape/artist/シユイ.JPG',
    artistImages: ['/grape/artist/シユイ.JPG', '/grape/artist/yama.JPG', '/grape/artist/スーパー登山部.JPG'],
    coverImage: '/grape/cover/シェアート FES 2026.JPG',
    venue: '下北沢LOFT',
    date: '2026-04-25',
    openingTime: '11:00',
    startTime: '12:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'payment-due',
    ticketDeadline: '2026-04-30',
    priority: 'high',
    price: 5500,
  },
  {
    id: 'l09',
    title: 'シェアート FES 2026（2日目）',
    artist: 'スーパー登山部',
    artists: ['スーパー登山部', 'Ado', 'yama'],
    artistImage: '/grape/artist/スーパー登山部.JPG',
    artistImages: ['/grape/artist/スーパー登山部.JPG', '/grape/artist/Ado.JPG', '/grape/artist/yama.JPG'],
    coverImage: '/grape/cover/シェアート FES 2026_2.JPG',
    venue: '下北沢LOFT',
    date: '2026-04-26',
    openingTime: '11:00',
    startTime: '12:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'waiting',
    announcementDate: '2026-04-01',
    ticketDeadline: '2026-04-05',
    priority: 'medium',
    price: 5500,
  },
  {
    id: 'l10',
    title: "Women's Voice 2026",
    artist: 'Ado',
    artists: ['Ado', '優利香'],
    artistImage: '/grape/artist/Ado.JPG',
    artistImages: ['/grape/artist/Ado.JPG', '/grape/artist/優利香.JPG'],
    venue: '横浜スタジアム',
    date: '2026-04-05',
    startTime: '17:00',
    endTime: '20:30',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    seatInfo: '未登録',
    announcementDate: '2026-04-01',
    priority: 'high',
    price: 8800,
  },
  {
    id: 'l11',
    title: 'LIGHTSのすゝめ CIRCUIT 2026',
    artist: 'yama',
    artistImage: '/grape/artist/yama.JPG',
    venue: 'TOKYO TOKYO',
    date: '2026-04-12',
    openingTime: '18:00',
    startTime: '18:30',
    endTime: '21:00',
    liveType: 'ワンマン',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    announcementDate: '2026-04-10',
    priority: 'medium',
    price: 4400,
  },
  {
    id: 'l12',
    title: 'Majorrity blues vol.11',
    artist: 'somei',
    artists: ['somei', 'シユイ'],
    artistImage: '/grape/artist/somei.JPG',
    venue: 'Milkyway',
    date: '2026-04-12',
    startTime: '20:00',
    endTime: '22:00',
    liveType: '対バン',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    price: 2500,
  },
  {
    id: 'l13',
    title: 'Make Happy!!',
    artist: 'スーパー登山部',
    artistImage: '/grape/artist/スーパー登山部.JPG',
    venue: 'Gee-ge',
    date: '2026-04-18',
    openingTime: '18:30',
    startTime: '19:00',
    endTime: '21:30',
    liveType: 'ワンマン',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    seatInfo: 'スタンディング',
    priority: 'low',
    price: 3000,
  },
  {
    id: 'l14',
    title: 'HAG ROCK FESTIVAL 2026GW',
    artist: 'yama',
    artists: ['yama', 'Ado', 'スーパー登山部', 'somei'],
    artistImage: '/grape/artist/yama.JPG',
    artistImages: ['/grape/artist/yama.JPG', '/grape/artist/Ado.JPG', '/grape/artist/スーパー登山部.JPG', '/grape/artist/somei.JPG'],
    venue: '横浜スタジアム',
    date: '2026-05-03',
    startTime: '10:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    seatInfo: '未登録',
    priority: 'high',
    price: 9800,
  },
  {
    id: 'l15',
    title: 'HAG ROCK FESTIVAL 2026GW day2',
    artist: 'Ado',
    artists: ['Ado', 'シユイ', 'yama'],
    artistImage: '/grape/artist/Ado.JPG',
    artistImages: ['/grape/artist/Ado.JPG', '/grape/artist/シユイ.JPG', '/grape/artist/yama.JPG'],
    venue: '横浜スタジアム',
    date: '2026-05-04',
    startTime: '10:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    price: 9800,
  },
  {
    id: 'l16',
    title: "Somei 1st ONE MAN LiVE『ASYLUM』追加公演",
    artist: 'somei',
    artistImage: '/grape/artist/somei.JPG',
    coverImage: "/grape/cover/Somei 1st ONE MAN LiVE『ASYLUM』.JPG",
    venue: 'WWW',
    date: '2026-05-10',
    openingTime: '17:30',
    startTime: '18:00',
    endTime: '20:30',
    liveType: 'ワンマン',
    attendanceStatus: 'planned',
    ticketStatus: 'waiting',
    ticketDeadline: '2026-04-20',
    price: 3500,
  },
  {
    id: 'l17',
    title: 'TAKE OFF LIVE',
    artist: 'シユイ',
    artistImage: '/grape/artist/シユイ.JPG',
    venue: 'TAKE OFF 7',
    date: '2026-05-16',
    startTime: '19:00',
    endTime: '21:00',
    liveType: 'ワンマン',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    price: 3000,
  },
  {
    id: 'l18',
    title: '下北沢 Daisy Bar/Laguna 奥崎海斗 presents「シェアート FES 2026」',
    artist: '優利香',
    artists: ['優利香', 'yama', 'スーパー登山部'],
    artistImage: '/grape/artist/優利香.JPG',
    artistImages: ['/grape/artist/優利香.JPG', '/grape/artist/yama.JPG', '/grape/artist/スーパー登山部.JPG'],
    coverImage: '/grape/cover/IMG_0173.JPG',
    venue: '下北沢LOFT',
    date: '2026-05-23',
    openingTime: '15:00',
    startTime: '16:00',
    endTime: '21:00',
    liveType: 'フェス',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    price: 4000,
  },
  {
    id: 'l19',
    title: 'Shibuya Fidd Out! Vol.3 追加公演',
    artist: 'シユイ',
    artistImage: '/grape/artist/シユイ.JPG',
    coverImage: '/grape/cover/Shibuya Fidd Out! Vol.3.JPG',
    venue: 'WWW',
    date: '2026-04-19',
    openingTime: '13:30',
    startTime: '14:00',
    endTime: '17:00',
    liveType: '対バン',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    price: 2500,
  },
  {
    id: 'l20',
    title: 'yama acoustic night',
    artist: 'yama',
    artistImage: '/grape/artist/yama.JPG',
    venue: 'Milkyway',
    date: '2026-04-19',
    startTime: '19:00',
    endTime: '21:00',
    liveType: '配信',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    price: 2000,
  },
]

// ─── Utility functions ───────────────────────────────────────────────────────

export function getLivesByDate(date: string): GrapeLive[] {
  return LIVES.filter((l) => l.date === date)
}

export function getLivesByMonth(year: number, month: number): GrapeLive[] {
  const prefix = `${year}-${String(month).padStart(2, '0')}`
  return LIVES.filter((l) => l.date.startsWith(prefix))
}

export function getUrgentLives(): GrapeLive[] {
  return LIVES.filter(
    (l) => l.ticketStatus === 'payment-due'
  )
}

export function getLivesWithTicketStatus(status: string): GrapeLive[] {
  return LIVES.filter((l) => l.ticketStatus === status)
}
