import type { GrapeLive, GrapeArtist } from './types'

// ─── Artists ────────────────────────────────────────────────────────────────

export const ARTISTS: GrapeArtist[] = [
  { id: 'aoi',      name: 'AOI',      image: '/grape/artist/soloA_ssw.png',   birthday: '2000-03-28' },
  { id: 'nana',     name: 'NANA',     image: '/grape/artist/soloB_RB.png',    birthday: '2000-05-23' },
  { id: 'mei',      name: 'MEI',      image: '/grape/artist/soloC.png',       birthday: '2000-04-12' },
  { id: 'koharu',   name: 'koharu',   image: '/grape/artist/soloD.png',       birthday: '2000-05-10' },
  { id: 'lumenade', name: 'lumenade', image: '/grape/artist/girlsgroup.png',  birthday: '2000-04-18' },
  { id: 'luna',     name: 'Luna',     image: '/grape/artist/vtuber.jpg',      birthday: '2000-04-05' },
]

// ─── Lives ───────────────────────────────────────────────────────────────────

export const LIVES: GrapeLive[] = [
  // ── 3月20日 同日2件 ────────────────────────────────────────────────────────
  {
    id: 'l05',
    title: 'Tokyo Street Live SHIBUYA',
    artist: 'NANA',
    artistImage: '/grape/artist/soloB_RB.png',
    coverImage: '/grape/cover/cover-citypop.png',
    venue: 'SHIBUYA PETAL STAGE',
    date: '2026-04-14',
    startTime: '15:30',
    endTime: '16:00',
    liveType: '対バン',
    attendanceStatus: 'planned',
    ticketStatus: 'pay-at-door',
    price: 0,
  },
  {
    id: 'l06',
    title: 'Tokyo Street Live SHIBUYA Day2',
    artist: 'AOI',
    artistImage: '/grape/artist/soloA_ssw.png',
    coverImage: '/grape/cover/cover-ssw.png',
    venue: '新宿 CROSSING SQUARE',
    date: '2026-04-14',
    openingTime: '16:30',
    startTime: '17:00',
    endTime: '17:30',
    liveType: '対バン',
    attendanceStatus: 'planned',
    ticketStatus: 'payment-due',
    ticketDeadline: '2026-04-20',
    priority: 'high',
    price: 2000,
  },

  // ── 3月末〜4月 ────────────────────────────────────────────────────────────
  {
    id: 'l08',
    title: 'PHAROS FES 2026',
    artist: 'MEI',
    artists: ['MEI', 'koharu', 'lumenade'],
    artistImage: '/grape/artist/soloC.png',
    artistImages: ['/grape/artist/soloC.png', '/grape/artist/soloD.png', '/grape/artist/girlsgroup.png'],
    coverImage: '/grape/cover/cover-festival.png',
    venue: '下北沢 LIGHTBOX',
    date: '2026-04-25',
    openingTime: '11:00',
    startTime: '12:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'payment-due',
    ticketDeadline: '2026-04-30',
    priority: 'high',
    price: 5500,
  },
  {
    id: 'l09',
    title: 'PHAROS FES 2026 Day2',
    artist: 'lumenade',
    artists: ['lumenade', 'Luna', 'koharu'],
    artistImage: '/grape/artist/girlsgroup.png',
    artistImages: ['/grape/artist/girlsgroup.png', '/grape/artist/vtuber.jpg', '/grape/artist/soloD.png'],
    coverImage: '/grape/cover/cover-group.png',
    venue: '下北沢 LIGHTBOX',
    date: '2026-04-26',
    openingTime: '11:00',
    startTime: '12:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    priority: 'medium',
    price: 5500,
  },
  {
    id: 'l11',
    title: 'LIGHTS CIRCUIT 2026',
    artist: 'koharu',
    artistImage: '/grape/artist/soloD.png',
    coverImage: '/grape/cover/cover-acoustic.png',
    venue: 'TOKYO STAGE',
    date: '2026-04-12',
    openingTime: '18:00',
    startTime: '18:30',
    endTime: '21:00',
    liveType: 'ワンマン',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    announcementDate: '2026-04-10',
    priority: 'medium',
    price: 4400,
  },
  {
    id: 'l13',
    title: 'POP-UP!!',
    artist: 'lumenade',
    artistImage: '/grape/artist/girlsgroup.png',
    coverImage: '/grape/cover/cover-group.png',
    venue: 'SEE-SEE',
    date: '2026-04-18',
    openingTime: '18:30',
    startTime: '19:00',
    endTime: '21:30',
    liveType: 'ワンマン',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    seatInfo: 'スタンディング',
    priority: 'low',
    price: 3000,
  },
  {
    id: 'l14',
    title: 'MOON ROCK FESTIVAL 2026 GW',
    artist: 'koharu',
    artists: ['koharu', 'Luna', 'lumenade', 'AOI'],
    artistImage: '/grape/artist/soloD.png',
    artistImages: ['/grape/artist/soloD.png', '/grape/artist/vtuber.jpg', '/grape/artist/girlsgroup.png', '/grape/artist/soloA_ssw.png'],
    coverImage: '/grape/cover/cover-festival.png',
    venue: 'みなとみらい ARENA',
    date: '2026-05-03',
    startTime: '10:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    seatInfo: '未登録',
    priority: 'high',
    price: 9800,
  },
  {
    id: 'l15',
    title: 'MOON ROCK FESTIVAL 2026 GW Day2',
    artist: 'Luna',
    artists: ['Luna', 'MEI', 'koharu'],
    artistImage: '/grape/artist/vtuber.jpg',
    artistImages: ['/grape/artist/vtuber.jpg', '/grape/artist/soloC.png', '/grape/artist/soloD.png'],
    coverImage: '/grape/cover/cover-rock.png',
    venue: 'みなとみらい ARENA',
    date: '2026-05-04',
    startTime: '10:00',
    endTime: '20:00',
    liveType: 'フェス',
    attendanceStatus: 'planned',
    ticketStatus: 'paid',
    price: 9800,
  },
  {
    id: 'l16',
    title: "AOI 1st ONE MAN LIVE『NOCTURNE』追加公演",
    artist: 'AOI',
    artistImage: '/grape/artist/soloA_ssw.png',
    coverImage: '/grape/cover/cover-ssw.png',
    venue: 'CAVE Shibuya',
    date: '2026-05-10',
    openingTime: '17:30',
    startTime: '18:00',
    endTime: '20:30',
    liveType: 'ワンマン',
    attendanceStatus: 'planned',
    ticketStatus: 'waiting',
    ticketDeadline: '2026-04-20',
    price: 3500,
  },
  {
    id: 'l17',
    title: 'DAYDREAM LIVE',
    artist: 'MEI',
    artistImage: '/grape/artist/soloC.png',
    venue: 'LIFT OFF 7',
    date: '2026-05-16',
    startTime: '19:00',
    endTime: '21:00',
    liveType: 'ワンマン',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    price: 3000,
  },
  {
    id: 'l18',
    title: 'PHAROS FES Satellite Showcase',
    artist: 'NANA',
    artists: ['NANA', 'koharu', 'lumenade'],
    artistImage: '/grape/artist/soloB_RB.png',
    artistImages: ['/grape/artist/soloB_RB.png', '/grape/artist/soloD.png', '/grape/artist/girlsgroup.png'],
    coverImage: '/grape/cover/cover-festival.png',
    venue: '下北沢 LIGHTBOX',
    date: '2026-05-23',
    openingTime: '15:00',
    startTime: '16:00',
    endTime: '21:00',
    liveType: 'フェス',
    attendanceStatus: 'candidate',
    ticketStatus: 'before-sale',
    price: 4000,
  },
  {
    id: 'l19',
    title: 'Indies Night Vol.3 追加公演',
    artist: 'MEI',
    artistImage: '/grape/artist/soloC.png',
    coverImage: '/grape/cover/cover-indie.png',
    venue: 'CAVE Shibuya',
    date: '2026-04-19',
    openingTime: '13:30',
    startTime: '14:00',
    endTime: '17:00',
    liveType: '対バン',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    price: 2500,
  },
  {
    id: 'l20',
    title: 'koharu acoustic night',
    artist: 'koharu',
    artistImage: '/grape/artist/soloD.png',
    coverImage: '/grape/cover/cover-acoustic.png',
    venue: 'MOONLIGHT',
    date: '2026-04-19',
    startTime: '19:00',
    endTime: '21:00',
    liveType: '配信',
    attendanceStatus: 'planned',
    ticketStatus: 'issued',
    price: 2000,
  },
]

// ─── Utility functions ───────────────────────────────────────────────────────

export function getLivesByDate(date: string): GrapeLive[] {
  return LIVES.filter((l) => l.date === date)
}

export function getLivesByMonth(year: number, month: number): GrapeLive[] {
  const prefix = `${year}-${String(month).padStart(2, '0')}`
  return LIVES.filter((l) => l.date.startsWith(prefix))
}

export function getUrgentLives(): GrapeLive[] {
  return LIVES.filter(
    (l) => l.ticketStatus === 'payment-due'
  )
}

export function getLivesWithTicketStatus(status: string): GrapeLive[] {
  return LIVES.filter((l) => l.ticketStatus === status)
}
